#
# Makefile for the amlogic video device interface device drivers.
#
EXTRA_AFLAGS=-mfloat-abi=softfp -mfpu=neon
amlvideodri-objs := amlvideo.o
amlcm-objs := common/vfutil.o

obj-y +=amlcm.o
obj-y +=amlvideodri.o 
